module.exports = {
  AUTH_SUCCESS: "#AUTH_SUCCESS;",
  AUTH_ERROR: '#AUTH_ERROR;',
  DEVICE_ERROR: '#DEVICE_ERROR;',
  DEVICE_NOT_FOUND: '#DEVICE_NOT_FOUND;',
  DEVICE_SEND_DATA: '#DEVICE_SEND_DATA;',
  DEVICE_RESCEIVED_DATA: '#DEVICE_SEND_DATA;',
  DEVICE_SETUP_OK: '#DEVICE_SETUP_OK;',
  DEVICE_SETUP_ERROR: '#DEVICE_SETUP_ERROR;',
  DEVICE_SETUP_ASSET_ERROR: '#DEVICE_SETUP_ASSET_ERROR;',
  DEVICE_ASSET_NOT_FOUND: '#DEVICE_ASSET_NOT_FOUND;',
  DEVICE_SETUP_ASSET_OK: '#DEVICE_SETUP_ASSET_OK;',
  DEVICE_ASSET_SEND_OK: '#DEVICE_ASSET_SEND_OK;',
  DEVICE_ASSET_SEND_ERROR: '#DEVICE_ASSET_SEND_OK;'
};
